[server]
rpc_urls = [
    "https://pub1.aplocoin.com",
    "https://pub2.aplocoin.com",
]

[wallet]
seed_phrase = ""
private_key = "0x..."
wallet_address = "0x..."

[contract]
contract_address = "0x..."

[miner]
max_wallets = 20
gas_thresholds = 0.01
token_withdrawal_multiplier = 0.001
log_level = 2
mining_threads_per_wallet = 4
blocks_to_wait = 20